version: '3.7'

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: 3.8

x-default-volumes: &default_volumes
  volumes:
    - ./:/app

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - ./database_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=picker
      - POSTGRES_PASSWORD=#
      - POSTGRES_DB=pricepicker-v2

  testdb:
    image: postgres:12
    volumes:
      - ./database_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db

  pricepicker-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "pricepicker-development"
    ports:
      - "5000:5000"
    <<: *default_volumes

    depends_on:
      - db
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      LOG_LEVEL: debug

  pricepicker-test:
    build:
      context: .
      target: test
      args:
        <<: *build_args
    image: "pricepicker-test"
    <<: *default_volumes

    depends_on:
      - testdb
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      LOG_LEVEL: debug
      DATABASE_TEST_URL: postgresql://test_user:test@testdb/test_db

  pricepicker-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "pricepicker-production"
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

volumes:
  postgres: