"""
This is place for all admin views.

Views should ALWAYS extend ProtectedModelView !

"""
from flask import redirect, url_for, request, flash, abort
from flask_admin import expose, helpers, AdminIndexView
from flask_admin.actions import action
from flask_admin.contrib.sqla import ModelView as _ModelView
from flask_login import current_user, login_user, logout_user

from project.server import flask_admin as admin, db
from project.server.models import Customer, MailLog, Shop, Order, Device, Manufacturer, Repair, Image, DeviceSeries, ReferralPartner
# Create customized model view class
from .column_formatters import customer_formatter, ref_formatter
from .forms import LoginForm, ChangePasswordForm
from ..models.device import Color


class ProtectedModelView(_ModelView):

    def is_accessible(self):
        """ All admin views require authentication """
        return current_user.is_authenticated

    def inaccessible_callback(self, name, **kwargs):
        """
        Redirect to login page if user doesn't have access
        """
        return redirect(url_for('admin.login_view', next=request.url))

    def _handle_view(self, name, **kwargs):
        """
        Override builtin _handle_view in order to redirect users when a view is not accessible.
        """
        if not self.is_accessible():
            if current_user.is_authenticated:
                abort(403)
            else:
                return redirect(url_for('admin.login_view', next=request.url))


class ProtectedIndexView(AdminIndexView):
    @expose('/')
    def index(self):
        """ Render the welcome page for the admin """
        if not current_user.is_authenticated:
            return redirect(url_for('.login_view'))
        return super(ProtectedIndexView, self).index()

    @expose('/login/', methods=('GET', 'POST'))
    def login_view(self):
        """ Logic to handle a user logging in """
        form = LoginForm(request.form)
        if helpers.validate_form_on_submit(form):
            user = form.get_user()
            if user:
                login_user(user)
            else:
                flash("Invalid Credentials")

        if current_user.is_authenticated:
            return redirect(url_for('.index'))

        self._template_args['form'] = form
        return super(ProtectedIndexView, self).index()

    @expose('/password/', methods=('GET', 'POST'))
    def change_password_view(self):
        """ Logic for updating a password """
        if not current_user.is_authenticated:
            abort(403)

        form = ChangePasswordForm(request.form)
        if helpers.validate_form_on_submit(form):
            current_user.password = form.new_password.data
            current_user.save()
            logout_user()
            flash("Password updated successfully. Please login again.", "success")
            return redirect(url_for('.login_view'))

        self._template_args['form'] = form
        return self.render('admin/password.html')

    @expose('/logout/')
    def logout_view(self):
        """ Logout """
        logout_user()
        return redirect(url_for('.index'))


class AdminExportableModelView(ProtectedModelView):
    """ This just enables the export option """
    can_export = True
    can_view_details = True
    details_modal = True


class UserModelView(AdminExportableModelView):
    """ User List + Creation """
    column_exclude_list = ['password_hash', ]


class CustomerListView(AdminExportableModelView):
    """ Customers are only listed and can be edited but not created """
    can_create = False

    column_editable_list = ['first_name', 'last_name', 'street', 'zip_code', 'city', 'tel', 'email']


class MailLogView(AdminExportableModelView):
    """ Mail logs are generated by celery and should be changed or created """
    can_create = False
    can_edit = False
    can_delete = False


class ShopView(AdminExportableModelView):
    """ Shop list view """
    form_excluded_columns = ['orders']

    column_editable_list = ['name']


class OrderView(AdminExportableModelView):
    """ View all orders """
    can_create = False
    can_edit = True

    column_hide_backrefs = False

    # Create a direct href to customer details
    column_formatters = dict(customer=customer_formatter)


class SubmittedOrderView(OrderView):
    """ Submitted Orders """
    can_delete = False

    column_list = ('timestamp', 'kva', 'shop', 'color', 'customer', 'repairs', 'problem_description', 'customer_wishes_shipping_label')

    def get_query(self):
        return self.session.query(self.model).filter(self.model.complete == True).order_by(self.model.timestamp.desc())  # noqa


class PendingOrderView(OrderView):
    """ Not submitted orders """
    list_template = "admin/order/pending.html"
    can_delete = True

    column_list = ('timestamp', 'color', 'customer', 'repairs', 'problem_description')

    def get_query(self):
        return self.session.query(self.model).filter(self.model.complete == False).order_by(self.model.timestamp.desc())  # noqa


class DeviceView(AdminExportableModelView):
    """ Create and manage devices """
    form_excluded_columns = ['orders', 'repairs']

    column_list = ('manufacturer', 'series', 'name', 'image', 'is_tablet', 'colors')
    column_filters = ('series.name', 'series.manufacturer.name')
    column_labels = {'series.name': 'Serie', 'series.manufacturer.name': 'Hersteller'}
    column_editable_list = ['series', 'image', 'is_tablet', 'name', 'colors']


class ColorView(AdminExportableModelView):
    """ Create and manage colors """
    form_excluded_columns = ['devices']

    column_editable_list = ['name', 'color_code']


class ManufacturerView(AdminExportableModelView):
    """ Create and manage manufacturers """
    form_excluded_columns = ['series']

    column_editable_list = ['name', 'image', 'activated']


class DeviceSeriesView(AdminExportableModelView):
    """ Series view """
    form_excluded_columns = ['devices']

    column_editable_list = ['name', 'manufacturer']


class RepairView(AdminExportableModelView):
    """ Repair View """
    form_excluded_columns = ['orders']

    column_editable_list = ['device', 'name', 'image', 'price']


class ImageView(AdminExportableModelView):
    """ Manage and view images  """
    form_excluded_columns = ['path']

    column_editable_list = ['name', 'device_default', 'tablet_default', 'repair_default', 'manufacturer_default']


class ReferralManagementView(AdminExportableModelView):
    """ Manage referral links and programs """
    form_excluded_columns = ['uuid', 'referrals']

    column_list = ('name', 'uuid', 'ref_link', 'total_referrals', 'un_billed_referral_count')
    column_labels = {'ref_link': 'Referral-Link', 'total_referrals': 'Referrals (absolut)', 'un_billed_referral_count': 'referrals (offen)'}

    # This creates a check mark that will mark all referrals as billed

    @action('bill', 'Abrechnen', 'Bist du sicher, dass alle ausgewählten Partner auf \'abgrechnet\' gesetzt werden sollen?')
    def action_bill(self, ids):
        for i in ids:
            p = ReferralPartner.query.get_or_404(i)
            p.bill()
        flash("Es wurden alle Referrals auf abgrechnet gesetzt!")
        return redirect(url_for('referralpartner.index_view', ), code=302)

    # Create a direct href to customer details
    column_formatters = dict(ref_link=ref_formatter)


# Register ModelViews

admin.add_view(CustomerListView(Customer, db.session, name="Kunden"))  # Customer
admin.add_view(SubmittedOrderView(Order, db.session, name="Aufträge", endpoint="orders"))  # Orders
admin.add_view(PendingOrderView(Order, db.session, name="Nicht abgeschlossene Aufträge", endpoint="pending"))  # Orders

admin.add_view(ManufacturerView(Manufacturer, db.session, name="Hersteller"))  # Manufacturers
admin.add_view(DeviceSeriesView(DeviceSeries, db.session, name="Serien"))  # Manufacturers
admin.add_view(DeviceView(Device, db.session, name="Geräte"))  # Devices
admin.add_view(RepairView(Repair, db.session, name="Reparaturen"))  # Repairs

admin.add_view(ShopView(Shop, db.session, name="Shop"))  # Shop
admin.add_view(ColorView(Color, db.session, name="Farben"))  # Colors
admin.add_view(ImageView(Image, db.session, name="Bilder"))  # Images

admin.add_view(MailLogView(MailLog, db.session, name="Email Log"))  # Mails

admin.add_view(ReferralManagementView(ReferralPartner, db.session, name="Referral Programm"))
