"""empty message

Revision ID: 281362c70f34
Revises: acff3391146d
Create Date: 2020-05-27 16:58:11.029790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '281362c70f34'
down_revision = 'acff3391146d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('color', 'color_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('color', 'internal_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('color', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('device_series', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('manufacturer', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manufacturer', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('device_series', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('color', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('color', 'internal_name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('color', 'color_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
