"""empty message

Revision ID: acff3391146d
Revises: 
Create Date: 2020-05-27 09:56:17.151902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acff3391146d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_city', table_name='customers')
    op.drop_index('ix_customers_email', table_name='customers')
    op.drop_index('ix_customers_first_name', table_name='customers')
    op.drop_index('ix_customers_last_name', table_name='customers')
    op.drop_index('ix_customers_street', table_name='customers')
    op.drop_index('ix_customers_tel', table_name='customers')
    op.drop_index('ix_customers_tricoma_id', table_name='customers')
    op.drop_index('ix_customers_zip_code', table_name='customers')
    op.drop_table('customers')
    op.drop_table('shops')
    op.add_column('color', sa.Column('internal_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_color_internal_name'), 'color', ['internal_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_color_internal_name'), table_name='color')
    op.drop_column('color', 'internal_name')
    op.create_table('shops',
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('name', name='shops_pkey')
    )
    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tricoma_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tricoma_username', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('tel', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('registered_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='customers_pkey')
    )
    op.create_index('ix_customers_zip_code', 'customers', ['zip_code'], unique=False)
    op.create_index('ix_customers_tricoma_id', 'customers', ['tricoma_id'], unique=False)
    op.create_index('ix_customers_tel', 'customers', ['tel'], unique=False)
    op.create_index('ix_customers_street', 'customers', ['street'], unique=False)
    op.create_index('ix_customers_last_name', 'customers', ['last_name'], unique=False)
    op.create_index('ix_customers_first_name', 'customers', ['first_name'], unique=False)
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_index('ix_customers_city', 'customers', ['city'], unique=False)
    # ### end Alembic commands ###
