"""empty message

Revision ID: acff3391146d
Revises: 
Create Date: 2020-05-27 09:56:17.151902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'acff3391146d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('color', sa.Column('internal_name', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_color_internal_name'), 'color', ['internal_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_color_internal_name'), table_name='color')
    op.drop_column('color', 'internal_name')
    # ### end Alembic commands ###
