"""drop custom affiliate tables

Revision ID: ede408a5aaf8
Revises: 82958e227684
Create Date: 2020-07-10 15:56:41.066293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ede408a5aaf8'
down_revision = '82958e227684'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_referral_partner_name', table_name='referral_partner')
    op.drop_table('referral')
    op.drop_table('referral_partner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('billed_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('partner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='referral_order_id_fkey'),
    sa.ForeignKeyConstraint(['partner_id'], ['referral_partner.id'], name='referral_partner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='referral_pkey'),
    sa.UniqueConstraint('order_id', name='referral_order_id_key')
    )
    op.create_table('referral_partner',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='referral_partner_pkey'),
    sa.UniqueConstraint('uuid', name='referral_partner_uuid_key')
    )
    op.create_index('ix_referral_partner_name', 'referral_partner', ['name'], unique=True)
    # ### end Alembic commands ###
