"""referral

Revision ID: f36523e7e9fa
Revises: 281362c70f34
Create Date: 2020-06-03 16:30:47.725616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f36523e7e9fa'
down_revision = '281362c70f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_partner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_referral_partner_name'), 'referral_partner', ['name'], unique=True)
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('partner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['partner_id'], ['referral_partner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral')
    op.drop_index(op.f('ix_referral_partner_name'), table_name='referral_partner')
    op.drop_table('referral_partner')
    # ### end Alembic commands ###
