"""ref timestamp

Revision ID: f7ca57091454
Revises: f36523e7e9fa
Create Date: 2020-06-03 17:02:53.041566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ca57091454'
down_revision = 'f36523e7e9fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.alter_column('referral', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('referral', 'partner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'referral', ['order_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral', type_='unique')
    op.alter_column('referral', 'partner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('referral', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('referral', 'timestamp')
    # ### end Alembic commands ###
