# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Testing on ${{ matrix.os }} with Python version ${{ matrix.python }}
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Test on Python 3.8 and ubuntu
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8']
        os: ['ubuntu-latest']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
          APP_SETTINGS: project.server.config.TestingConfig
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: pricepicker
          postgresql user: postgres
          postgresql password: postgres

      # Runs the tests
      - name: Setup python
        uses: actions/setup-python@v1
        with:
            python-version: ${{ matrix.python }}
            architecture: x64

      - name: Install requirements
        run: pip install -r requirements_dev.txt
      
      - name: Activate PG_TRIM
        run: PGPASSWORD=postgres psql -h 127.0.0.1 -U postgres pricepicker -c "CREATE EXTENSION pg_trgm;"

      - name: Run tests with coverage and create report as xml file
        run: python manage.py cov

      - name: Run Flake8
        run: flake8 project
