name: CI

on: [pull_request]

jobs:
  build:
    name: Testing on ${{ matrix.os }} with Python version ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: ['3.8']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v1

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests with coverage and create report as xml file
        run: python manage.py cov

      - name: Run Flake8
        run: flake8

